name: Track Exercises on Runner

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - run: docker pull exercism/zig-test-runner
      - name: Run tests for all exercises
        run: sh ./bin/test
