name: Track Exercises on Runner

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - run: docker pull exercism/zig-test-runner
      - name: Run tests for all exercises
        run: sh ./bin/test
