name: Track Exercises on Runner

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: docker pull exercism/zig-test-runner
      - name: Run tests for all exercises
        run: sh ./bin/test
